package pl.szadowek91.day3;

/**
 * @author PG
 */
public class InputData {

    public static final String TEST_RUCKSACK = "" +
            "vJrwpWtwJgWrhcsFMMfFFhFp\n" +
            "jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL\n" +
            "PmmdzqPrVvPwwTWBwg\n" +
            "wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn\n" +
            "ttgJtRGJQctTZtZT\n" +
            "CrZsJsPPZsGzwwsLwLmpwMDw";

    public static final String FINAL_RUCKSACK = "" +
            "NGvdqJmJvpNbGRMGQgRsfgfn\n" +
            "WlHTHShlLwSWjFRsncfbcwsgQc\n" +
            "BHtSBHWHSCWLZHlhjTHLLdbNNqNpzpDzNvDvtPmmPp\n" +
            "JJSShnTpDSJJlllfwBNVbMQWwhQhgQtt\n" +
            "cTzrvrHdLwwzttQNWB\n" +
            "qrFqTFvqZvrmsplsjlnDflnZ\n" +
            "mhhhVHvNNddHMwBqQwlWZZtv\n" +
            "fbjzjJllCtWjjrZtjq\n" +
            "CbgcgpPRDJfzVHFFnSnsSDlm\n" +
            "ZqBPqBQnPLmqZsFqhsvFsLZQMfSSMbbWddWbjbJSrgWgJf\n" +
            "NRHnlllcDwwCNClNtttHbNJrSJNfbdWMdfbWgdrJ\n" +
            "cHGlzTptHtCpncHnCpHpRGzDmvVhqLmvLPmPvLqPmzsqqmPB\n" +
            "rCzVtMMbMvCmmvGlclFQFfLpJFJfJpcLHPJL\n" +
            "nDGGwqGqnRTfpHLpRFpLFf\n" +
            "ZNdNTDsWgNZsZBndnGrzrlMrjgrmjVGjvC\n" +
            "MgFZHFTgqFFDZZDTdVdHrzQvLzCGwpCPrGLqQpzz\n" +
            "JsnmbjhmffJbRNJppzPPzwzzrwdv\n" +
            "lfblfthBRbBRjnjhBtBlZgdVcFSTVFDtSSWgMcdM\n" +
            "hPVhVhWPCMhlDTTWdrPlTcLjfbZbFNjZBbFNBbdBFbsB\n" +
            "MHSwMJpHnqJHwtqHGqGGmvqZsZFjBmsBNRBFfLbsFsZfsZ\n" +
            "pqtMHHQpvqnwMpgJMCChTQhVVlclPWrCCD\n" +
            "zRBBhZFwWZlBQpMZNNNJsfDpLsNsJppN\n" +
            "SvggPbjvVSvvtgGVPbbnSMcCLtMrDddssJdsLdfdCD\n" +
            "mTSmMgHjgmgGgqzTwZwBlBFzwB\n" +
            "WLzWZHWSZPFRVSPSPM\n" +
            "hmrvmGvfTCmhBGBqTfnmJFfdbQcwdMhMwRdbQMVQQcMhsQ\n" +
            "JGJJnrnnCmqBTJTrNBqBLDzHFLFDNgjZlWtDNZHL\n" +
            "bwbbnWwpbTwFHwRzzzmH\n" +
            "ZccjZjddjPVhJmrBQHHFQRHcWF\n" +
            "NVhWldsMjZZZLSnvSTGTgvMb\n" +
            "ccJbHpzccZJsNpJCmHHlBTgHnlTPmF\n" +
            "qvQGQfDVhhDfvVfVDSdDCbFnjmllPQjlbCmnFgjg\n" +
            "hSbtWRGvhdfDVdVRfvRNpsWsZLNMZzcswLZWMM\n" +
            "vlTdlBTMdtjcvLGmtb\n" +
            "SSgfSsJngCSSwNFgspHFNFFpjlbGjQbbQGLthLnWtmWWhjbm\n" +
            "SJsfqqgfNHwJfHgCpwzBZVMDBPMMRPTlqzBr\n" +
            "VHsVhtbRHRpVHBfBCJdNfGjggGJdqLGq\n" +
            "wSzSrrSMPDSDwzPjdqJjNwGdsLqGjj\n" +
            "MnrnQTnWZWWzWQDMvZhtHtshhHlHBcBBsvVt\n" +
            "DZbPqdTqGTZtRrzjFmZZtF\n" +
            "gjQwVvBVWgfghvgmcrBNFccHFRmHtF\n" +
            "QlgvWlfgVsQfdlqqjqPDbPlM\n" +
            "VcfLwwcMlpnfVDrDtrtvbjMtTM\n" +
            "mmgBgzSQmQdgHBFSLvvbDTJmTDvTJJDr\n" +
            "RWNBHHzWNSdSdzFgSLNWWfZGwfpcwWVnnfpCCWlV\n" +
            "GDZLtsJMFGLDPnbblJlNJNcJ\n" +
            "BBRgSwqwqRZhTVSqjVgRwCdQcmcPmdnPPnPnmjlrbmQj\n" +
            "RCqfVvhfCCShBCRfVCwztDGZMHpLWHftFptspF\n" +
            "dlZqlBfBSShZhvprbCJTDrJCJjJNDh\n" +
            "WGRwQwHsMVVGMsVGcRVtQWRVpNCjWNDbzbDNJnbnrCbprrNW\n" +
            "HgHRRVGGwLgLBPvgSp\n" +
            "QPlZSlZzVLLDwhDfBppf\n" +
            "bghGGhmqrspDcfbsbs\n" +
            "tTrdTgFddtnvmdgvtCTdGTTqFZjjQQPVZPSZSjlZhVVQjlRS\n" +
            "BgBFHnwwSTNHqSPN\n" +
            "GJmCbDdlbZGCLhsstNLsMZZZ\n" +
            "JGJpCCDvmlVDVldGJBVfBBRwRjnVWWBRfN\n" +
            "WTFWQgGQtTMqMCJJzDVDgCchhj\n" +
            "mNPBmPlPHrWmwmNLHmShcnJjhrnzJzdcdzdjJJ\n" +
            "SHssNRSmvPRmlsmLwwsmwLvpQptpQWMQbGFQFtfpFfZQ\n" +
            "DgpNLVjgNjjmzGPVRmfrZrctdTcrzfwzdfMc\n" +
            "bnbNqnbFNwMcMtMfwF\n" +
            "svCQHHhShnbCvHChsvHlLDVhJJLRJGNpgPJPjLLD\n" +
            "TmBzgTVVBgfbmTVfPmFRJcHctnHDLDDLJqqBGB\n" +
            "hwvlNCCvSphMwSvrlwCCrrDcfRlJDLRtGqcqHnqRqLGR\n" +
            "pMSSMMNCSwMjjWhwrrjShQNFmsPmPFWbbZzVfZsPPPZVmZ\n" +
            "sTTrWGCMggpVWhSBltWp\n" +
            "HNJdwLDzNcJnNLwJJPqpllqhBpqStjfwlfpj\n" +
            "PJHzDzFLtLccdLggvrGGmgvFssgG\n" +
            "FwCssBFRBlvbBVdQ\n" +
            "jPzjDpqNGqJzZGSNHppPclFvvdfVflblbJlmFfll\n" +
            "SDzDpSNqjZjjZFSrHrFZTTCMLsnTLnnnMhrLtLnn\n" +
            "ScWQvvSDddGrWVrG\n" +
            "fwhPFLpwTfTjrzwHdmmmGdgdsPsqdRmV\n" +
            "CHlFpTpwwCjwFjwjCBnrvQBZZcBSnZtvZl\n" +
            "vJvdWVNslWtJcDtDHrDf\n" +
            "GCnnMZpZnSZpvDqFtftfjfZqrh\n" +
            "TbGMSRCRvWbPNsWB\n" +
            "NNNdsRddGNdZZTCBtqbtBgtC\n" +
            "zhFHppHhzcgmzQhccjgmjhQTnvvBFtBnCBbbnTvtCCtntt\n" +
            "HpjmhfSjQwfzwHmcggfzjSLfVWPDsWMsMdWdDSMsGWPPllVN\n" +
            "WSvcSSwrGzFsznqPNNWqPqlllB\n" +
            "djVDdHdSPRqlntjN\n" +
            "LpZZgpLgLHTDHVpDSTsffvGwrcfffGwv\n" +
            "wGlbWGVvGlWlrvppbFMjQjsBjCsjmCzzQzNv\n" +
            "ZgfdJcfZhMNCgSBRCQRz\n" +
            "hcLDZPZdqZhJPhcTHJfPHVqlqtFWMrGGrpwVGVpWrV\n" +
            "dsngCgdssHDVsHdsFDvMDvmMmjTjDFTL\n" +
            "qZpSqptZZGWLTLSjlLHFzl\n" +
            "NZqqRpWqhQpNhqhpZRWBJQQssJbbCsdbHsCbgb\n" +
            "QdGBjjbHsBsBbBdGcwwTGrCRRrFcPPTC\n" +
            "ZDtvWfMDvWScSrpzPccCdr\n" +
            "hhZMgffDhZNvtDgHQsQQVQmBVVHNdV\n" +
            "LhQLrzVdVmqcjmTNzm\n" +
            "tHMZDJDZCDDtZMWwCJjcffqqfjRmqSRqcq\n" +
            "CpHpZZWWtWpWwBplZWmQbhVBVPhnPrhbLQPvvs\n" +
            "FFgFSmJmSgGpZzsmgGmbDlDzMQPDNPzRQRDjQQzV\n" +
            "CLwnwWBdrtthttTWBWdPnVvRVVVNMSVQPvVnnV\n" +
            "BTtdLthfhTrLdftCwqrddmGFcSfpGbsmFGHpmGFHHc\n" +
            "JFJnMZwQBqnJJBqZJqPqMFBlbmBHblWbrmlfbWgbvmWrgW\n" +
            "spCTjtVzsNDdsNdTsjVTtNzgHfmWWgHSSrgrbSbbhHbVHS\n" +
            "TfCdjjsjzLNsfTszcdqcQMnRMPPRnFRPQRFP\n" +
            "VvDgDqTDtTNWTWfNFWlW\n" +
            "pzPvdssRNQFQRNZF\n" +
            "CCpBpsrrccGvttgGqBDG\n" +
            "jmZrrjlCJqmCVFMPbFbBZPVp\n" +
            "dfLLfRMGTdHbssPLLPbFwL\n" +
            "QWWHHTRQdRRHRMhzWQfvddngqJqjjNgqqjlgvrtjJmtn\n" +
            "sGGwJdHDDTfWbTcRzbbz\n" +
            "BmjvdhNVlFBZmSZvFrWpfpcBrbzbWcbqpf\n" +
            "SLmSZLhNhMhwtLswPHGssd\n" +
            "mGhlPclTmhhlJRWlRTDPlJtTFMngBcLSBHHBHLHSwncFgLwB\n" +
            "jQVbjprjVfzbZQrzdGnHrrBLgSGwGFLHHg\n" +
            "zzZqjQjdvsRlGqThGJ\n" +
            "GSPQPvVmSwpVQGVlSQmWJRcFBpnFBcBWcJcJDc\n" +
            "rTTCLmhTTbZNqMNbhjfhmDzsFDWzsDnfcBWDDDzcFs\n" +
            "qmjhrhCtbMCZNhZMhNTZbLjvQdHdHGgwgdtQHlllQwlQgv\n" +
            "ggpCCgvjPTJWjBjWWJgCWCdVVHRZdLfZhqLdZRHZrf\n" +
            "GsstmNslzzzGlMnGMnVZRZrLpZqdhZHZrZHM\n" +
            "lNbDsbltmzpsmmmnnccBJTwPgWvvvTwPwFPS\n" +
            "FWbTRTdWGCnThqQVBQqJ\n" +
            "rrDMPrDcSrvtcJdLVhVHQMQVBQ\n" +
            "rNtNwrZtDNPmZStwvcvRlGFRlzCRlpmdpplbpb\n" +
            "gHrHrlFgjCrNDfCMTzwwLN\n" +
            "WhvTvvWnmQvpGWNNLzwWfNzW\n" +
            "vTnRZhnRRBhscBVpcBTvnsjFltPqggqHPHHjHrPcgrFg\n" +
            "VzfWRVsnNzWfsvpQPvvFbdVQpQ\n" +
            "SqCqqhLDTTCTTCDcSdbpPvdPFFvhMbdMvF\n" +
            "BCLBDCDGLlTClCSrglrGzWmrszzmHRJmfJfJpHNz\n" +
            "dwGBHGdwdcCMCBzzZJJssZFsBBgt\n" +
            "NRqbRbQhLQRLrQlTggFWlZtRlTvW\n" +
            "FbNDFDLqnmLmNbqbLQbhLNDpPcVHMSVMwCVHcPnVGccwjdcM\n" +
            "LdHtrrrHrLZrBVbQjtPnnsVb\n" +
            "TwfhhcTCTCpfJJwpTJwhDDPnbGsbFjlQnnQjFBFslsBQDl\n" +
            "pwJCThfRCMMMvhchhwHSmWLZHLNHMdrdZzPg\n" +
            "LbMQbHbHQLLMsWLvszvzvqCfqCCqss\n" +
            "ScWlpmplWrDzlzvznJ\n" +
            "RNNcZWhSZmdVdPwHbQQTTwNwjP\n" +
            "jFFFtHZjwmLNmnQCFL\n" +
            "sVbdsqcqHBHqrQrLPmWqQnmr\n" +
            "sfGJVVzJJsczczfsczBzzvdbTMTptlTZZgDSDtGlplZSlgHt\n" +
            "MgMQJdqqMDQJDggzTMgVplvffmctcCzmfjRlmmmjjR\n" +
            "HrGbGswnBBtRvccBlljB\n" +
            "HZPHRRGGshZHnnnwPnshnVZqMJJDdpQDVgDdVDWDpQ\n" +
            "whwQRQGHRVhWRRcLLJgLmL\n" +
            "jSnnzgBnpCZdCBjNmnNNJmllJTlccT\n" +
            "jPSzrzpzpCjgfZZrZCFpdwQDQVVPttGDtVqQVtHqth\n" +
            "mvnGFmvGhTcSCBcBpv\n" +
            "bwMRzbQLwBQRWSctCcTtLpss\n" +
            "JJgHZqRrbqDnmBjhDh\n" +
            "MVvvGrsbGtVsgTggHjSFHJBBBg\n" +
            "PPNpCpQPZppplttDNwZPBdfTFPPTSBWSFjjSTH\n" +
            "CpNwChQCzDDNZwhZlpwZpqrqsGGsmmctGbbbzcmMms\n" +
            "pjMbgCgdQjCgBjQQCncwcGGLDZvFtGLsZZFZtH\n" +
            "zPhhrVhVVSmqVqhmzPqvDtsLLHrFWFvGFGFsvt\n" +
            "SVPzVTzJNBfjDQbQTb\n" +
            "CRDjjRmmLhjRFFChmHDNLZzsZNnPZNzlnnsvlv\n" +
            "SSqcMwdrctQVtqTwSSgnvZnsZvnBZpcPsvlvbz\n" +
            "trMGSSVdQQqdGMtwwQCmRHHhmJFhsfJGfjHh\n" +
            "phJzrnJJwNNSJhSnwpwGGZzmvNfmmDvfcvcDfvbRPNcvvR\n" +
            "tWtgQBqsqdLFLmZvTRTfDZcb\n" +
            "ttssdgQqsHQtZFsqVdgdgdCBJGSphnljnJhjwrhnpJrrzJHl\n" +
            "srzpVWrWTptbrPpPPtcWpNhNNNdfhhDgDNvfBDNNds\n" +
            "jmnQHmLqlnSlGMjqnLLljRHqdNdgwHZBgfhZvBdNhDwBhhtZ\n" +
            "MjSlnLmMLnCGjlSQLVWCzbrcTpPtpFbFWr\n" +
            "ZnQRczHZsMSRZQcBRSZRscQwJbWFbbQwpWTjdFLJTJTWwd\n" +
            "PVmGqDlGhDPVNvqDmmqtqLbbpJfFJwpbdJpdbfdjwdbl\n" +
            "VGNCgGPgqVqhNvmNCNZnSsRLRsMzzgBRnHrS\n" +
            "ZgMMgJMhjmZrZgggmlTTbfwTfRfbRGwlGTDf\n" +
            "nPqQttNVPzSPnqpGDwDDbGfwbJ\n" +
            "dJvQzzJtdSPWSthhHMjgMvrHghsv\n" +
            "cMvwHCWcMnwWnScWVFzTqHpHFpVBFtFp\n" +
            "bbblgRDhtlGgRPFBRqFpmzVFBTFp\n" +
            "fPbtGJGhfDfDsPhQJDPbbnjjSWnwjdvQCnSSCnCSCM\n" +
            "NcgDtwghTLntgNtLrjfHSSFlSbCfprlL\n" +
            "ZGGMmdmVZVvsRQvMGRVVZCHPfpZSfZbFPlbPjCfH\n" +
            "RVRjvRzMQQJBVmzzgWgzTWTWhNcWzN\n" +
            "gsgBqdsWprWddpBghBpwwJzbLcvhCZmwZCFcJC\n" +
            "PRPtStHfwmJvzPmF\n" +
            "HnSHHRQDVFsVVgsgTWsG\n" +
            "QRQTRrDHSLSNzzZLzZ\n" +
            "dBmPwfwffWtWRtzdhhLzLzLzzLFN\n" +
            "BtWnWCCVBWtCBmRPqVmqmntjjlJHJslJQVsQjsbbHrjHDQ\n" +
            "TwwJrHSMnHGvWHMvvSqrrZbRrRqfqVNfbNRc\n" +
            "GjhstmPFFhlFtmmjQtlgVcZVfcgqqNRNpgRcbP\n" +
            "CzdCdFCtdzGWGJwWWHdW\n" +
            "zfSVfSpHVpCHSZLnsttDnvDvpcsqRc\n" +
            "rWzMGWFFPBFjqjDjFDFs\n" +
            "PbQQWbJPrQwPrrPBwrJCVzZZLZdLSLLmfZfHJd\n" +
            "gPDPLgsLNslNLHqlLqqjhjnwwjJbDjnjwTRnGD\n" +
            "tzdMdMddmcRMdtcFFGWnwWjFwjFhGbTG\n" +
            "mRMmttpVHNCNpNZN\n" +
            "mfCFGfDDFCDWtvvstjjJ\n" +
            "njnVnrggLlwVVqLpvHVpMpMsHVhhMW\n" +
            "QQPPPnjlPPSgwBrnNLcdFCNNGFbmbZFcZzFf\n" +
            "NzNHFNFnFrtgwwPchvGFFS\n" +
            "LsjdQCVsTsLCTTdMCJtQgPPqwhPgqScPGvSZ\n" +
            "jdLdVjJtCVjRCMpmpNfNNWHrNzDrNrHrmr\n" +
            "NmggPPrPbPmdCbcfCNLVRRWpWTWRVTpdVVWspW\n" +
            "qGhDzGqnwGQnJrjllJWttMRDFRtMVsTDTTZs\n" +
            "SrnHhGQlvLmSfbfc\n" +
            "DmdPCJMLlQdSjGCqjcGGccHH\n" +
            "zWtBwfsgvVnBfftWtnnpTmnTRhppHpTqpc\n" +
            "wzFtwZWmsVFzZtvPJSPbMFJFDJJJJd\n" +
            "wrPRRSJSWrTSRzRWrqlfCLlcBfBGDqrL\n" +
            "gVNQjgdVhdfqqhlDCBDs\n" +
            "NmjgbtmNtjNnjbPbvRJPbpwZwZSD\n" +
            "tNHGccGNthtSGmVjjVmrrVPqSB\n" +
            "fgDTwRwDFmLTFlspBBqjjBgqBssB\n" +
            "mLCZwZRMJMbtdWMtvd\n" +
            "TPzHPPgChjsgPdPTjQvZLvnpLQnvlRQn\n" +
            "GScFSzFWWrfGGMrVFMqGqmrBnplmwmnlZZlmnvvvLRnJLLvJ\n" +
            "qVSVFtFtFtSzrTNNDsHhhNTHht\n" +
            "NQqtqmqmNhvvclvhcljJ\n" +
            "CSCfMZSgWMvfWgrbjwcMJwrrrclr\n" +
            "CGSCZgSGZPRTSCWWDgGBRtnFRvqNRsLLzmsLzqpq\n" +
            "tWmtCZjnWZWCGjtnnmtcwFvvlgSDTDTvVwsVgCfT\n" +
            "LpLhpLdqbBMNsQPBQhpLvgFqllgfllvVvwTDTwlw\n" +
            "pNQBBdLbBPpPHLmGsRWjRZJzWZHc\n" +
            "WtjBSvBjWzTtzvDTjBfbbthsMNRNgCMQDgRcCcQwLRgCQgNc\n" +
            "HJmqnHqHpplVnlPdqGrpGQNLCgSwLMwFwFFCgnMLRw\n" +
            "SdJGpHVZmqpVVVdZVJGddsjvzzvZTsZvWTbvszWjWj\n" +
            "FhRhhLZgLZhCRWZBFFWRmGbvSgHqvvbPvHTPccVncb\n" +
            "wzSMpjJdwssdrdDfJJJsJSvpGVPqGpvVqTVqTnccnTvH\n" +
            "rwfMMdtDjNwjzDrjDDdtChRZWSWhmCWBSmLQRW\n" +
            "RWLNLWrhtrhWJmLnSStBBdVtBGVVBt\n" +
            "wQqnzjCFbflqpQlQFTDDGGsGDBZBSZMsDVfG\n" +
            "QvqCTwjjTqwbTqjznFzQvqjFJgmvgghJgPmgmvPNmNRJJNgN\n" +
            "qLqwhztjhqqDDzjZqqjPMmFmCnVDsmgbggggTMDC\n" +
            "WBhWJQrJcRmnFnWMTTCF\n" +
            "lvvJSlGSvBvJQBrcpSfwwLjLPjLfhptjwNtp\n" +
            "sbFjnZpPPGZLZzCRhqbJhJMCqMgS\n" +
            "vtNvFHBcNwNDHffvtfQMSMJVRMBMChVqSMCBJV\n" +
            "cQlvTffDlFWTlcfFTlHQNtzzGGWGdLsGWdrnzspjGdGr\n" +
            "LMQtlzlMQLLrztVfVdfqDdrhrhdd\n" +
            "JPJTHcvPTPTJGPZgbmvGPmcZhwRVdDBdSWfdRHSBfqBSVHqq\n" +
            "sJchPZGccmcbvcmgmPcCnnnnpzppQppspFjQntMl\n" +
            "qtQQtsMDqtPDGQltPHbsLFnMccRNcVLLrVNVwMVM\n" +
            "LCSdzZdBZmvzZTCBfJrwnWppFcWrFpdRnWpR\n" +
            "ThSgBZTLJmPHlgQHjPtq\n" +
            "mrwGPrVrbjbPVmwmbdTwbGfJMDJMgsqhhDjsqjJppfqt\n" +
            "SQnLnWnWHLSFCRnlQRnFhqfsDMJMppqDfcWgpDfD\n" +
            "NCSvLQnRSQFBLBzdgvTbbwPrzbPZ\n" +
            "FFjvvHZbHZnZpvFHZcFbgQVwgwQnJfQPVNQJGqSq\n" +
            "RWmCmdClRtTzVRwVfVQPNQgN\n" +
            "shwhzTsmlbhZDLbBHL\n" +
            "PpPHllshHDTlsprJrsPQpltzjVzjLNggZNznLNLnhNnnjL\n" +
            "qRBvSwqBdRqvmfvCRSSLjcnVcVmLgmnNZjmQVg\n" +
            "vdfbSfBWffMbQqQdtprtslHJsWDGHptt\n" +
            "pqQdFWlQZpGZpLpS\n" +
            "wnjwJhjvVgjwvwvsgwgtsRTtssGTtLrNtrSrHS\n" +
            "VDJVMGCCChjccDJDwgwVJvMBzBfzbzbDPPFBFBbffzbQqq\n" +
            "gBwwBZGhcfhnFjvrQjMhrjQQ\n" +
            "PPLJNdNldlNSRmzLSlpbHQvbvdMtjjbMtMtt\n" +
            "lqDJmlSmlmPzqNmzmVnvnBZDgvBWgcZTfD\n" +
            "HMqrwWqzWJqHzrjgGFNNtQFMFQnFBt\n" +
            "LddPLdVmchPSvmcvTZlvghLLFBDNDtFGDQpRnntnFDQnFPnB\n" +
            "SbSvZTSLSgqbCHJWzr\n" +
            "TGcjzjgtNqjttgNNTTjmGwLhfQQfDnDLDwSQWTSCvh\n" +
            "PHJRJJbBVMPRMJHbJRMPbwCQSSvfCDhVhvvwwvQLnW\n" +
            "ZJPMbHbJJJsdsJplRRRZsPJztrFrqtzGrgmcrprcmFjDgN\n" +
            "tlDpSbpwgbgtpddJppgJwJDtNQWGQlcGQGhlhnGGWcrcWWFr\n" +
            "MTZLqzjfFLqLjRfvqsQhNPGnhGGsnchW\n" +
            "LMCzjzMTTjjFRfZMBTCvRfLRDDbVVpSbSgwwwtSBSSDJgStg\n" +
            "ZLVTrJmJDHFtzSTlpc\n" +
            "wNhhNfhvwwvvfvPnsNPhglszqpcHcFbbFSzSzzCHzb\n" +
            "NWjPwgNgRHGWvhwWPfgfGwjMDQJdQLVLJLQVVLRdBRJrZr\n" +
            "CPRJCFJTqZfJlJRqssHJftCWQMnHHwMbbngMMrQMgMWwQn\n" +
            "BmzVVhvvcvDdWgwVrTnrMb\n" +
            "BjzvhjLLczzBjLchDLmLJtsCqFClTqsZCPtPTCjq\n" +
            "DbWjNCWQCRRNsDPpFGcjjcqFqFfm\n" +
            "PZdMSzSZTtZZqVmpqmmmTpgg\n" +
            "ZvZMzBztzvhvddPMQlNCQDbQLBLrsRRW\n" +
            "WzWFhHpWhvCpPpPLswMHswMMHLbgmH\n" +
            "NNZSZTVQNrTnqDqrrwtwwLstsMGMnbntGm\n" +
            "TBmQcrNqNSQVmrmQBPdpFFzhFlPzzCPF\n" +
            "nBgmSrjgmjtmrbjSFGLWtLVpFVQQVGFL\n" +
            "JlChvCzvqCqWffwFdFVQfPVPHPFGLV\n" +
            "JzvTThZcCCMcMMwJzlbjTjmnRgRTTBnWgbBn\n" +
            "rppjbbDpGnwrGprVCLLJZDzQqZzLNQqc\n" +
            "htflFBFmBBlWTTgsggtZHMQLCCCcHqHMfZczHq\n" +
            "gFdFTWgRhBmWWTFSGQbVnSSPnvndpv\n" +
            "qFSRRGGgTgThTQhcllCWCJCctWWhfJ\n" +
            "bvbdzNDMzHZNNHFHfJWWjljWNNfcnWtn\n" +
            "PdbPdPBHmsdbdbPdBHBdmdmsgrTqsGQRTwSpSFrqrRSFpRwp\n" +
            "pQJZZGQtChQtpWZQTTWhNtVdVWSLBrsLSVrLvrvrLdBd\n" +
            "lMHnzGRgPRMSMBLcvBSS\n" +
            "nglFzflzHRDGgzfzPgHRbTDQthbZbhhppNbbCqhb\n" +
            "jVrvrJjpZfZCCGctwhbhMRcM\n" +
            "BQQnFFTBdBndzssFsdTbRwDGTPGbcMbwtDgbcG\n" +
            "HnLtQQBLtWNrVpqjJvWN\n" +
            "dnVlsnJlMqnlNqJdnMRvDHBRvbBLHLpRSPPPRS\n" +
            "NcGGCthFwcFwmjCTGDSfPSSHSPfPtDHfbD\n" +
            "zNWNZGWNzQnWlJWVJn\n" +
            "tMGSBtRtvjFcGpQrQQQQrp\n" +
            "FffbJTJfPLNbTnJJmlVcQVfpQmlWVVfH\n" +
            "FTdJJdhNvZhMtRSh\n" +
            "pSTfMtMLSTPsPsBszP\n" +
            "jdlmlFHHhVdmVHFNFRnHzHQJsGZBJbbJDvsDRPBsrGrDrJ\n" +
            "VHnFjcdccjlmNVmnzmNVmCMggfqwtLLfSMwWtcWMSg";

}